spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: create
    open-in-view: false

  data:
    rest:
      base-path: /data-api

logging:
  level:
    root: info
    org.springframework.security: debug